name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          AUTHOR_USERNAME: ${{ github.actor }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
          
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "embeds": [{
                "author": {
                  "name": "'"$COMMIT_AUTHOR"'",
                  "icon_url": "https://github.com/'"$AUTHOR_USERNAME"'.png"
                },
                "title": "Commit to '"$REPO_NAME"' (main)",
                "description": "There has been 1 commit to **['"$REPO_NAME"']('"$COMMIT_URL"')**\n\n```diff\n+ Modified 1 files\n```",
                "color": 5067519,
                "fields": [
                  {
                    "name": "`'"$COMMIT_HASH"'`",
                    "value": "```'"$COMMIT_MESSAGE"'```",
                    "inline": false
                  }
                ],
                "footer": {
                  "text": "'"$TIMESTAMP"'"
                }
              }]
            }' $DISCORD_WEBHOOK
